### ISSUE TITLE
Interactive elements should be focusable

### ISSUE THREAD

**Issue by HarshCasper** [beautifulinteractions/beautiful-react-diagrams#88]
**Describe the bug**
While going through the Code in `index-tests.tsx` I found this particular block of Code: 

```
      render: ({ content, data }) => (
        <div
          onDoubleClick={data?.onDoubleClick}
          role='button'
          style={{ padding: '15px', background: 'purple' }}
        >
          {content}
        </div>
```

Here the Interactive elements should be focusable. According to this [resource](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#Accessibility_concerns) : 

```
Buttons are interactive controls and thus focusable. If the button role is 
added to an element that is not focusable by itself (such as <span>, 
<div> or <p>) then, the tabindex attribute has to be used to make the button focusable.
```

This can be fixed by using the `tabIndex` as per my best knowledge.

**Comment by antonioru** [comment]
Hi @HarshCasper 
thank you very much for your feedback, I really appreciate it. 
The code you're looking at is a test related only to the typescript exported types, so even if the resource you linked is completely right, there's no need to update the code. 
On the other hand, if you want to open a PR  to fix this so that it will be accessible even in tests, I'll be happy to receive it 

Thank you

**Comment by antonioru** [comment]
@HarshCasper I'm going to close this issue, please feel free to open any other in case you need to
